language: cpp
env:
  global:
  - TRAVIS_BUILD_DOCS=true
  - DOXYFILE=Doxyfile
  - GH_REPO_NAME=tricl
  - TRAVIS_BUILD_DIR=src
branches:
  only:
  - master
before_install:
  - sudo apt-get -y install doxygen doxygen-doc doxygen-gui graphviz
#after_success:
  - |-
    echo "A"
    if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
      echo "B"
      cd $PROJECT_DIR_ABS
      pwd
      echo "C"
      source .ci/setup-ssh.sh || travis_terminate 1
      echo "D"
      .ci/generateDocumentation.sh || travis_terminate 1
      echo "E"
    fi
script: cmake . && cmake --build .
